language: php

php:
  - 7.4

install:
  - composer install

script:
  - ./vendor/bin/phpunit tests/unit

jobs:
  include:
    - stage: Code Quality
      script: vendor/bin/phpcs --standard=Doctrine src
