name: CI
on:
  workflow_dispatch:
  push:
  release:
    types: [published]

env:
  PHP: '/usr/bin/php7.4'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /tmp/snapshot-caches/
          key: "cachekey-${{ runner.os }}-${{ hashFiles('composer.lock') }}-qa-key"
          restore-keys: cachekey-${{ runner.os }}-

      - run: make install-ci
      - run: make test
